version: '3'

services:
  # PHP service
  php:
    build:
      context: ./php
    volumes:
      - ../laravel:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
